import React, { useEffect, useState } from 'react';
import { CheckCircle, AlertTriangle, Download, ArrowLeft, Eye, EyeOff, Info } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { toPng } from 'html-to-image';
import { jsPDF } from 'jspdf';
import { generateHeatmapOverlay } from '../utils/heatmap';
import { getIRCReference } from '../utils/compliance';

export default function ResultScreen() {
    const navigate = useNavigate();
    const [result, setResult] = useState(null);
    const [isExporting, setIsExporting] = useState(false);
    const [showHeatmap, setShowHeatmap] = useState(false);
    const [heatmapImage, setHeatmapImage] = useState(null);

    useEffect(() => {
        const currentData = localStorage.getItem('current_scan');
        if (currentData) {
            const parsed = JSON.parse(currentData);
            setResult(parsed);

            // Pre-generate heatmap if degraded
            if (parsed.classification === 'Degraded' && parsed.imageDataURL) {
                const img = new Image();
                img.onload = () => {
                    const overlay = generateHeatmapOverlay('Degraded', img);
                    setHeatmapImage(overlay);
                };
                img.src = parsed.imageDataURL;
            }
        }
    }, []);

    if (!result) {
        return (
            <div className="p-6 flex items-center justify-center h-full">
                <p className="text-gray-500">No scan data found. Go back and capture a scan.</p>
            </div>
        );
    }

    const exportPDF = async () => {
        try {
            setIsExporting(true);
            const input = document.getElementById('report-container');
            const imgData = await toPng(input, { cacheBust: true, pixelRatio: 2 });
            const pdf = new jsPDF('p', 'mm', 'a4');
            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = (input.offsetHeight * pdfWidth) / input.offsetWidth;
            
            // Header
            pdf.setFontSize(16);
            pdf.setTextColor(225, 29, 72);
            pdf.text("RetroScan AI - Inspection Report", 14, 20);
            pdf.setFontSize(10);
            pdf.setTextColor(100, 100, 100);
            pdf.text(`Timestamp: ${result.date} ${result.time || ''}`, 14, 28);
            pdf.text(`GPS Coordinates: ${result.lat}, ${result.lng}`, 14, 34);
            pdf.text(`Classification: ${result.classification} (${result.confidence}% confidence)`, 14, 40);
            pdf.text(`Estimated RA: ${result.estimatedRA} cd/lux/m²`, 14, 46);
            pdf.text(`Compliance: ${result.complianceLabel} | Condition: ${result.conditionLabel}`, 14, 52);
            pdf.text(getIRCReference(result.condition), 14, 58);

            // UI screenshot
            pdf.addImage(imgData, 'PNG', 14, 66, pdfWidth - 28, pdfHeight * ((pdfWidth - 28) / pdfWidth));
            
            // Footer
            const footerY = pdf.internal.pageSize.getHeight() - 20;
            pdf.setFontSize(8);
            pdf.text("Generated by RetroScan AI | IRC 67:2012 & IRC 35:2015 Compliant", 14, footerY);
            pdf.text("Site Engineer Signature: _______________________", 14, footerY + 8);
            
            pdf.save(`NHAI_Report_${Date.now()}.pdf`);
        } catch (e) {
            alert("Error exporting PDF: " + e.message);
            console.error(e);
        } finally {
            setIsExporting(false);
        }
    };

    // Color classes based on classification
    const classColors = {
        High: { bg: 'bg-green-500/10', text: 'text-green-500', border: 'border-green-500/30', bar: 'bg-green-500' },
        Medium: { bg: 'bg-amber-500/10', text: 'text-amber-500', border: 'border-amber-500/30', bar: 'bg-amber-500' },
        Degraded: { bg: 'bg-red-500/10', text: 'text-red-500', border: 'border-red-500/30', bar: 'bg-red-500' },
    };
    const colors = classColors[result.classification] || classColors.Degraded;

    return (
        <div className="p-6 max-w-md mx-auto w-full animate-in fade-in duration-500 pb-24 h-full overflow-y-auto">
            <button onClick={() => navigate(-1)} className="mb-4 text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white flex items-center gap-2 transition-colors">
                <ArrowLeft className="w-5 h-5" /> Back
            </button>
            <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-6 text-center">Scan Analysis</h2>
            
            <div id="report-container" className="bg-surface border border-primary/20 rounded-3xl p-6 text-center shadow-xl space-y-5">
                
                {/* Captured Image / Heatmap */}
                <div className="relative w-full aspect-video rounded-xl overflow-hidden border border-gray-700 bg-black">
                    {result.imageDataURL ? (
                        <img 
                            src={showHeatmap && heatmapImage ? heatmapImage : result.imageDataURL} 
                            alt="Captured sign" 
                            className="w-full h-full object-cover transition-opacity duration-300"
                        />
                    ) : (
                        <div className="w-full h-full flex items-center justify-center text-gray-500">
                            No image captured
                        </div>
                    )}
                    <div className="absolute top-2 left-2 bg-black/70 px-2 py-1 rounded text-xs font-mono text-gray-300">
                        {result.lat}, {result.lng}
                    </div>
                    {/* Condition badge */}
                    <div className="absolute top-2 right-2 bg-black/70 px-2 py-1 rounded text-xs text-gray-300">
                        {result.conditionIcon} {result.conditionLabel}
                    </div>
                </div>

                {/* Heatmap toggle (only for Degraded) */}
                {result.classification === 'Degraded' && heatmapImage && (
                    <button
                        onClick={() => setShowHeatmap(!showHeatmap)}
                        className={`w-full py-2 rounded-lg text-sm font-medium flex items-center justify-center gap-2 transition-colors ${
                            showHeatmap 
                                ? 'bg-red-500/20 text-red-400 border border-red-500/30' 
                                : 'bg-gray-500/10 text-gray-400 border border-gray-500/20'
                        }`}
                    >
                        {showHeatmap ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                        {showHeatmap ? 'Hide Heatmap' : 'View Degradation Heatmap'}
                    </button>
                )}

                {/* Classification Badge */}
                <div className={`${colors.bg} border ${colors.border} rounded-xl p-4`}>
                    <div className="flex items-center justify-between">
                        <div className="text-left">
                            <p className="text-xs text-gray-500 uppercase tracking-wider">Classification</p>
                            <p className={`text-2xl font-bold ${colors.text}`}>{result.classification}</p>
                        </div>
                        <div className={`p-3 rounded-full ${colors.bg}`}>
                            {result.complianceLabel === 'PASS' ? (
                                <CheckCircle className="w-10 h-10 text-green-500" />
                            ) : (
                                <AlertTriangle className={`w-10 h-10 ${colors.text}`} />
                            )}
                        </div>
                    </div>

                    {/* Confidence bar */}
                    <div className="mt-3">
                        <div className="flex justify-between text-sm mb-1">
                            <span className="text-gray-500">Confidence</span>
                            <span className={`font-semibold ${colors.text}`}>{result.confidence}%</span>
                        </div>
                        <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2.5">
                            <div 
                                className={`h-2.5 rounded-full ${colors.bar} transition-all duration-1000 ease-out`}
                                style={{ width: `${result.confidence}%` }}
                            />
                        </div>
                    </div>
                </div>

                {/* RA Value */}
                <div>
                    <div className="text-5xl font-mono font-bold text-accent mb-1">
                        {result.estimatedRA || result.score}
                    </div>
                    <div className="text-gray-400 text-sm uppercase tracking-widest">
                        cd / lux / m²
                    </div>
                </div>

                {/* Compliance Status */}
                <div className={`inline-flex items-center gap-2 px-4 py-2 rounded-full text-sm font-semibold ${
                    result.complianceLabel === 'PASS' ? 'bg-green-500/20 text-green-400' :
                    result.complianceLabel === 'MARGINAL' ? 'bg-amber-500/20 text-amber-400' :
                    'bg-red-500/20 text-red-400'
                }`}>
                    <span className="text-lg">{result.complianceIcon}</span>
                    {result.complianceLabel}
                </div>

                {/* Details Grid */}
                <div className="grid grid-cols-2 gap-4 border-t border-gray-200 dark:border-gray-800 pt-5">
                    <div className="text-left">
                        <p className="text-xs text-gray-500 dark:text-gray-500 uppercase">Threshold</p>
                        <p className="font-semibold text-gray-800 dark:text-gray-200">{result.threshold} cd/lux/m²</p>
                    </div>
                    <div className="text-left">
                        <p className="text-xs text-gray-500 dark:text-gray-500 uppercase">Condition</p>
                        <p className="font-semibold text-gray-800 dark:text-gray-200">{result.conditionIcon} {result.conditionLabel}</p>
                    </div>
                    <div className="text-left">
                        <p className="text-xs text-gray-500 dark:text-gray-500 uppercase">Inference Time</p>
                        <p className="font-semibold text-gray-800 dark:text-gray-200">{result.inferenceTime || 0}ms</p>
                    </div>
                    <div className="text-left">
                        <p className="text-xs text-gray-500 dark:text-gray-500 uppercase">Timestamp</p>
                        <p className="font-semibold text-gray-800 dark:text-gray-200">{result.time}</p>
                    </div>
                </div>

                {/* Probability breakdown */}
                {result.probabilities && (
                    <div className="border-t border-gray-200 dark:border-gray-800 pt-5">
                        <p className="text-xs text-gray-500 uppercase mb-3 flex items-center gap-1">
                            <Info className="w-3 h-3" /> Class Probabilities
                        </p>
                        <div className="space-y-2">
                            {[
                                { label: 'High', value: result.probabilities.high, color: 'bg-green-500' },
                                { label: 'Medium', value: result.probabilities.medium, color: 'bg-amber-500' },
                                { label: 'Degraded', value: result.probabilities.degraded, color: 'bg-red-500' },
                            ].map(({ label, value, color }) => (
                                <div key={label} className="flex items-center gap-3 text-sm">
                                    <span className="w-20 text-left text-gray-500">{label}</span>
                                    <div className="flex-1 bg-gray-200 dark:bg-gray-700 rounded-full h-2">
                                        <div className={`h-2 rounded-full ${color} transition-all duration-700`} style={{ width: `${value}%` }} />
                                    </div>
                                    <span className="w-10 text-right font-mono text-gray-600 dark:text-gray-400">{value}%</span>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* IRC Reference */}
                <div className="text-xs text-gray-500 dark:text-gray-600 pt-2 border-t border-gray-200 dark:border-gray-800">
                    {getIRCReference(result.condition)}
                </div>
            </div>

            {/* Export PDF Button */}
            <button 
                onClick={exportPDF} 
                disabled={isExporting}
                className="w-full mt-6 bg-surface border border-primary/30 py-4 rounded-xl text-gray-800 dark:text-gray-200 flex items-center justify-center gap-2 hover:bg-primary/10 transition-colors shadow-lg disabled:opacity-50"
            >
                <Download className="w-5 h-5" />
                {isExporting ? "Generating PDF..." : "Export IRC-Compliant PDF"}
            </button>
        </div>
    );
}
